### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by smileart** [knq/usql#25]
Hey there! Unfortunately, current installation as it recommended in the documentation doesn't work due to (as it seems to me) dependencies issue e.g. when I do:

```shell
go get -u -tags most github.com/knq/usql
```

As a result I get this error message:

```shell
# cd /Users/username/.go/src/github.com/akrennmair/goauth; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/akrennmair/goauth: exit status 1
```

Not sure is it something I can fix locally or you could do it on your side, but currently for me the default installation just doesn't do the trick.

Just in case, my current system and env:

```shell
ProductName: Mac OS X
ProductVersion: 10.12.4
BuildVersion: 16E195
Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
go version go1.8 darwin/amd64
```

**Comment by kenshaw** [comment]
This is a configuration problem with the `goauth` repo. I get this same error all the time, as well. The problem is that the author / maintainer of that repo has changed the default configured branch (I think?), so this error comes up. What you need to do is just change to the directory with that repository (`cd $GOPATH/src/github.com/akrennmair/goauth` and then just force a checkout to the master branch:

```
git checkout master && git pull
```
You should then be able to do the `go get -u`. Sorry about this, but it's out of my control (short of removing the dependency on this package). For the record, `go get` is more or less just a convenience wrapper around Git (and other source control systems), and it would be great if they could recognize/fix this in the Go tool itself.

I'll take a look at what part is using this, as I don't believe anything in the `usql` code is directly using this package.

(for the record, I also get this same problem with other repositories that even much larger apps like Docker use!)

**Comment by smileart** [comment]
I see. Thanks for such a detailed explanation! Really appreciate it. Cheers.
