### ISSUE TITLE
Binary Oracle driver?

### ISSUE THREAD

**Issue by thorstenkampe** [knq/usql#28]
Is the Oracle driver available as an external binary download? I am not able to build usql with Oracle support...

**Comment by kenshaw** [comment]
Please see the instructions on the [rana/ora](https://github.com/rana/ora) driver for installing Oracle support. From the top of my head:

1. Download and install the Oracle `instantclient-*` SDK
2. Create a `oci8.pc` file for `pkg-config` somewhere in your `$PKG_CONFIG_PATH` path
3. Build using `-tags oracle`

You may want to look at the `contrib/grab-oracle.sh` script, which downloads this in an automated fashion, and is used in the travis configuration for building/testing purposes. 

Due to legal/copyright issues, we can't release a `usql` binary that's linked against the Oracle `instantclient` SDK
