### ISSUE TITLE
Describe command doesn't work for mysql on ubuntu 14.04

### ISSUE THREAD

**Issue by tenken** [knq/usql#29]
Hi --

Thanks for this nice sql tool. In general it's lightyears faster than phpmyadmin and other GUI based applications which is why I'm seeking to utilize it more in my workflows.

I've noticed the `DESCRIBE` command seems to be not providing useful data from my MySQL database.

I figured maybe describe was MySQL specific, but I don't see it listed here:
https://dev.mysql.com/doc/refman/5.7/en/extensions-to-ansi.html

The example test queries I'm executing are:
```sql
my:dev_user@localhost/_drupal=> describe papers_diff_06262017_prepared_inline_content;
DESCRIBE
my:dev_user@localhost/_drupal=> DESCRIBE papers_diff_06262017_prepared_inline_content;
DESCRIBE
my:dev_user@localhost/_drupal=> DESC papers_diff_06262017_prepared_inline_content;
DESC
```
Other system information:
```txt
my:dev_user@localhost/_drupal=> \conninfo
Connected with driver mysql (dev_user:dev@tcp(localhost:3306)/_drupal?loc=Local&parseTime=true&sql_mode=ansi)

$ ./usql --version
usql 0.5.0

$ mysql --version
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3
```

**Comment by kenshaw** [comment]
For now, you can use `EXPLAIN` which is a synonym in MySQL for `DESCRIBE`. 

The issue here is that `usql` doesn't have any real "understanding" of a SQL query, and since this is Go, you need to know ahead of time if the sent query should be executed or has results (ie, `Exec` vs `Query`). This is an oversight on my part, and I'll add the `DESC` and `DESCRIBE` aliases to the `drivers/qtype.go` file so that this can be dealt with. Appreciate you surfacing this.
